package maydo.ocpp.msgDef.Messages;


import com.google.gson.JsonObject;
import maydo.ocpp.msgDef.DataTypes.Address;
import maydo.ocpp.msgDef.DataTypes.CustomData;
import maydo.ocpp.msgDef.Enumerations.PaymentStatusEnum;
import maydo.ocpp.msgDef.JsonInterface;
import maydo.ocpp.msgDef.annotations.Optional;
import maydo.ocpp.msgDef.annotations.Required;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Objects;

import static maydo.ocpp.config.Configuration.DATE_FORMAT;

public class NotifySettlementRequest implements JsonInterface {

    /**
     * The _transactionId_ that the settlement belongs to. Can be empty if the payment transaction is canceled prior to the start of the OCPP transaction.
     */
    @Optional
    private String transactionId;
    /**
     * The payment reference received from the payment terminal and is used as the value for _idToken_.
     * <p>
     * <p>
     * (Required)
     */
    @Required
    private String pspRef;
    /**
     * The status of the settlement attempt.
     * <p>
     * <p>
     * (Required)
     */
    @Required
    private PaymentStatusEnum status;
    /**
     * Additional information from payment terminal/payment process.
     */
    @Optional
    private String statusInfo;
    /**
     * The amount that was settled, or attempted to be settled (in case of failure).
     * <p>
     * <p>
     * (Required)
     */
    @Required
    private Float settlementAmount;
    /**
     * The time when the settlement was done.
     * <p>
     * <p>
     * (Required)
     */
    @Required
    private Date settlementTime;
    @Optional
    private String receiptId;
    /**
     * The receipt URL, to be used if the receipt is generated by the payment terminal or the CS.
     */
    @Optional
    private String receiptUrl;
    /**
     * *(2.1)* A generic address format.
     */
    @Optional
    private Address vatCompany;
    /**
     * VAT number for a company receipt.
     */
    @Optional
    private String vatNumber;
    /**
     * This class does not get 'AdditionalProperties = false' in the schema generation, so it can be extended with arbitrary JSON properties to allow adding custom data.
     */
    @Optional
    private CustomData customData;

    /**
     * No args constructor for use in serialization
     */
    public NotifySettlementRequest() {
    }

    /**
     * @param pspRef           The payment reference received from the payment terminal and is used as the value for _idToken_.
     *                         <p>
     *                         .
     * @param statusInfo       Additional information from payment terminal/payment process.
     *                         <p>
     *                         .
     * @param settlementTime   The time when the settlement was done.
     *                         <p>
     *                         .
     * @param settlementAmount The amount that was settled, or attempted to be settled (in case of failure).
     *                         <p>
     *                         .
     * @param receiptUrl       The receipt URL, to be used if the receipt is generated by the payment terminal or the CS.
     *                         <p>
     *                         .
     * @param transactionId    The _transactionId_ that the settlement belongs to. Can be empty if the payment transaction is canceled prior to the start of the OCPP transaction.
     *                         <p>
     *                         .
     * @param vatNumber        VAT number for a company receipt.
     *                         <p>
     *                         .
     */
    public NotifySettlementRequest(String transactionId, String pspRef, PaymentStatusEnum status, String statusInfo, Float settlementAmount, Date settlementTime, String receiptId, String receiptUrl, Address vatCompany, String vatNumber, CustomData customData) {
        super();
        this.transactionId = transactionId;
        this.pspRef = pspRef;
        this.status = status;
        this.statusInfo = statusInfo;
        this.settlementAmount = settlementAmount;
        this.settlementTime = settlementTime;
        this.receiptId = receiptId;
        this.receiptUrl = receiptUrl;
        this.vatCompany = vatCompany;
        this.vatNumber = vatNumber;
        this.customData = customData;
    }

    /**
     * The _transactionId_ that the settlement belongs to. Can be empty if the payment transaction is canceled prior to the start of the OCPP transaction.
     */
    public String getTransactionId() {
        return transactionId;
    }

    /**
     * The _transactionId_ that the settlement belongs to. Can be empty if the payment transaction is canceled prior to the start of the OCPP transaction.
     */
    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId;
    }

    /**
     * The payment reference received from the payment terminal and is used as the value for _idToken_.
     * <p>
     * <p>
     * (Required)
     */
    public String getPspRef() {
        return pspRef;
    }

    /**
     * The payment reference received from the payment terminal and is used as the value for _idToken_.
     * <p>
     * <p>
     * (Required)
     */
    public void setPspRef(String pspRef) {
        this.pspRef = pspRef;
    }

    /**
     * The status of the settlement attempt.
     * <p>
     * <p>
     * (Required)
     */
    public PaymentStatusEnum getStatus() {
        return status;
    }

    /**
     * The status of the settlement attempt.
     * <p>
     * <p>
     * (Required)
     */
    public void setStatus(PaymentStatusEnum status) {
        this.status = status;
    }

    /**
     * Additional information from payment terminal/payment process.
     */
    public String getStatusInfo() {
        return statusInfo;
    }

    /**
     * Additional information from payment terminal/payment process.
     */
    public void setStatusInfo(String statusInfo) {
        this.statusInfo = statusInfo;
    }

    /**
     * The amount that was settled, or attempted to be settled (in case of failure).
     * <p>
     * <p>
     * (Required)
     */
    public Float getSettlementAmount() {
        return settlementAmount;
    }

    /**
     * The amount that was settled, or attempted to be settled (in case of failure).
     * <p>
     * <p>
     * (Required)
     */
    public void setSettlementAmount(Float settlementAmount) {
        this.settlementAmount = settlementAmount;
    }

    /**
     * The time when the settlement was done.
     * <p>
     * <p>
     * (Required)
     */
    public Date getSettlementTime() {
        return settlementTime;
    }

    /**
     * The time when the settlement was done.
     * <p>
     * <p>
     * (Required)
     */
    public void setSettlementTime(Date settlementTime) {
        this.settlementTime = settlementTime;
    }

    public String getReceiptId() {
        return receiptId;
    }

    public void setReceiptId(String receiptId) {
        this.receiptId = receiptId;
    }

    /**
     * The receipt URL, to be used if the receipt is generated by the payment terminal or the CS.
     */
    public String getReceiptUrl() {
        return receiptUrl;
    }

    /**
     * The receipt URL, to be used if the receipt is generated by the payment terminal or the CS.
     */
    public void setReceiptUrl(String receiptUrl) {
        this.receiptUrl = receiptUrl;
    }

    /**
     * *(2.1)* A generic address format.
     */
    public Address getVatCompany() {
        return vatCompany;
    }

    /**
     * *(2.1)* A generic address format.
     */
    public void setVatCompany(Address vatCompany) {
        this.vatCompany = vatCompany;
    }

    /**
     * VAT number for a company receipt.
     */
    public String getVatNumber() {
        return vatNumber;
    }

    /**
     * VAT number for a company receipt.
     */
    public void setVatNumber(String vatNumber) {
        this.vatNumber = vatNumber;
    }

    /**
     * This class does not get 'AdditionalProperties = false' in the schema generation, so it can be extended with arbitrary JSON properties to allow adding custom data.
     */
    public CustomData getCustomData() {
        return customData;
    }

    /**
     * This class does not get 'AdditionalProperties = false' in the schema generation, so it can be extended with arbitrary JSON properties to allow adding custom data.
     */
    public void setCustomData(CustomData customData) {
        this.customData = customData;
    }

    @Override
    public String toString() {
        return toJsonObject().toString();
    }

    @Override
    public JsonObject toJsonObject() {
        JsonObject json = new JsonObject();
        json.addProperty("transactionId", transactionId);
        json.addProperty("pspRef", pspRef);
        json.addProperty("status", status.toString());
        json.addProperty("statusInfo", statusInfo);
        json.addProperty("settlementAmount", settlementAmount);
        json.addProperty("settlementTime", new SimpleDateFormat(DATE_FORMAT).format(settlementTime));
        json.addProperty("receiptId", receiptId);
        json.addProperty("receiptUrl", receiptUrl);
        json.add("vatCompany", vatCompany.toJsonObject());
        json.addProperty("vatNumber", vatNumber);
        json.add("customData", customData.toJsonObject());
        return json;
    }

    @Override
    public void fromString(String jsonString) {
    }

    @Override
    public void fromJsonObject(JsonObject jsonObject) {
        if (jsonObject.has("transactionId")) {
            this.transactionId = jsonObject.get("transactionId").getAsString();
        }

        if (jsonObject.has("pspRef")) {
            this.pspRef = jsonObject.get("pspRef").getAsString();
        }

        if (jsonObject.has("status")) {
            this.status = PaymentStatusEnum.valueOf(jsonObject.get("status").getAsString());
        }

        if (jsonObject.has("statusInfo")) {
            this.statusInfo = jsonObject.get("statusInfo").getAsString();
        }

        if (jsonObject.has("settlementAmount")) {
            this.settlementAmount = jsonObject.get("settlementAmount").getAsFloat();
        }

        if (jsonObject.has("settlementTime")) {
            try {
                SimpleDateFormat dateFormat = new SimpleDateFormat(DATE_FORMAT);
                this.settlementTime = dateFormat.parse(jsonObject.get("settlementTime").getAsString());
            } catch (ParseException e) {
                System.out.println("Invalid date format for settlementTime" + e);
            }
        }

        if (jsonObject.has("receiptId")) {
            this.receiptId = jsonObject.get("receiptId").getAsString();
        }

        if (jsonObject.has("receiptUrl")) {
            this.receiptUrl = jsonObject.get("receiptUrl").getAsString();
        }

        if (jsonObject.has("vatCompany")) {
            this.vatCompany = new Address();
            this.vatCompany.fromJsonObject(jsonObject.getAsJsonObject("vatCompany"));
        }

        if (jsonObject.has("vatNumber")) {
            this.vatNumber = jsonObject.get("vatNumber").getAsString();
        }

        if (jsonObject.has("customData")) {
            this.customData = new CustomData();
            this.customData.fromJsonObject(jsonObject.getAsJsonObject("customData"));
        }

    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (!(obj instanceof NotifySettlementRequest))
            return false;
        NotifySettlementRequest that = (NotifySettlementRequest) obj;
        return Objects.equals(this.pspRef, that.pspRef)
                && Objects.equals(this.statusInfo, that.statusInfo)
                && Objects.equals(this.vatCompany, that.vatCompany)
                && Objects.equals(this.settlementTime, that.settlementTime)
                && Objects.equals(this.customData, that.customData)
                && Objects.equals(this.settlementAmount, that.settlementAmount)
                && Objects.equals(this.receiptUrl, that.receiptUrl)
                && Objects.equals(this.receiptId, that.receiptId)
                && Objects.equals(this.transactionId, that.transactionId)
                && Objects.equals(this.status, that.status)
                && Objects.equals(this.vatNumber, that.vatNumber);
    }

    @Override
    public int hashCode() {
        int result = 1;
        result = 31 * result + (this.pspRef != null ? this.pspRef.hashCode() : 0);
        result = 31 * result + (this.statusInfo != null ? this.statusInfo.hashCode() : 0);
        result = 31 * result + (this.vatCompany != null ? this.vatCompany.hashCode() : 0);
        result = 31 * result + (this.settlementTime != null ? this.settlementTime.hashCode() : 0);
        result = 31 * result + (this.customData != null ? this.customData.hashCode() : 0);
        result = 31 * result + (this.settlementAmount != null ? this.settlementAmount.hashCode() : 0);
        result = 31 * result + (this.receiptUrl != null ? this.receiptUrl.hashCode() : 0);
        result = 31 * result + (this.receiptId != null ? this.receiptId.hashCode() : 0);
        result = 31 * result + (this.transactionId != null ? this.transactionId.hashCode() : 0);
        result = 31 * result + (this.status != null ? this.status.hashCode() : 0);
        result = 31 * result + (this.vatNumber != null ? this.vatNumber.hashCode() : 0);
        return result;
    }
}
