package maydo.ocpp.msgDef.Messages;

import com.google.gson.JsonObject;
import maydo.ocpp.msgDef.DataTypes.CustomData;
import maydo.ocpp.msgDef.JsonInterface;
import maydo.ocpp.msgDef.annotations.Optional;

import java.util.Objects;

public class NotifySettlementResponse implements JsonInterface {

    /**
     * The receipt URL if receipt generated by CSMS. The Charging Station can QR encode it and show it to the EV Driver.
     */
    @Optional
    private String receiptUrl;
    /**
     * The receipt id if the receipt is generated by CSMS.
     */
    @Optional
    private String receiptId;
    /**
     * This class does not get 'AdditionalProperties = false' in the schema generation, so it can be extended with arbitrary JSON properties to allow adding custom data.
     */
    @Optional
    private CustomData customData;

    /**
     * No args constructor for use in serialization
     */
    public NotifySettlementResponse() {
    }

    /**
     * @param receiptUrl The receipt URL if receipt generated by CSMS. The Charging Station can QR encode it and show it to the EV Driver.
     *                   <p>
     *                   .
     * @param receiptId  The receipt id if the receipt is generated by CSMS.
     *                   <p>
     *                   .
     */
    public NotifySettlementResponse(String receiptUrl, String receiptId, CustomData customData) {
        super();
        this.receiptUrl = receiptUrl;
        this.receiptId = receiptId;
        this.customData = customData;
    }

    /**
     * The receipt URL if receipt generated by CSMS. The Charging Station can QR encode it and show it to the EV Driver.
     */
    public String getReceiptUrl() {
        return receiptUrl;
    }

    /**
     * The receipt URL if receipt generated by CSMS. The Charging Station can QR encode it and show it to the EV Driver.
     */
    public void setReceiptUrl(String receiptUrl) {
        this.receiptUrl = receiptUrl;
    }

    /**
     * The receipt id if the receipt is generated by CSMS.
     */
    public String getReceiptId() {
        return receiptId;
    }

    /**
     * The receipt id if the receipt is generated by CSMS.
     */
    public void setReceiptId(String receiptId) {
        this.receiptId = receiptId;
    }

    /**
     * This class does not get 'AdditionalProperties = false' in the schema generation, so it can be extended with arbitrary JSON properties to allow adding custom data.
     */
    public CustomData getCustomData() {
        return customData;
    }

    /**
     * This class does not get 'AdditionalProperties = false' in the schema generation, so it can be extended with arbitrary JSON properties to allow adding custom data.
     */
    public void setCustomData(CustomData customData) {
        this.customData = customData;
    }

    @Override
    public String toString() {
        return toJsonObject().toString();
    }

    @Override
    public JsonObject toJsonObject() {
        return null;
    }

    @Override
    public void fromString(String jsonString) {
    }

    @Override
    public void fromJsonObject(JsonObject jsonObject) {
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (!(obj instanceof NotifySettlementResponse))
            return false;
        NotifySettlementResponse that = (NotifySettlementResponse) obj;
        return Objects.equals(this.customData, that.customData)
                && Objects.equals(this.receiptUrl, that.receiptUrl)
                && Objects.equals(this.receiptId, that.receiptId);
    }

    @Override
    public int hashCode() {
        int result = 1;
        result = 31 * result + (this.customData != null ? this.customData.hashCode() : 0);
        result = 31 * result + (this.receiptUrl != null ? this.receiptUrl.hashCode() : 0);
        result = 31 * result + (this.receiptId != null ? this.receiptId.hashCode() : 0);
        return result;
    }
}
