package maydo.ocpp.msgDef.Messages;


import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import maydo.ocpp.msgDef.DataTypes.Address;
import maydo.ocpp.msgDef.DataTypes.CustomData;
import maydo.ocpp.msgDef.Enumerations.PaymentStatusEnum;
import maydo.ocpp.msgDef.JsonInterface;
import maydo.ocpp.msgDef.annotations.Optional;
import maydo.ocpp.msgDef.annotations.Required;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Objects;

import static maydo.ocpp.config.Configuration.DATE_FORMAT;

/**
 *
 */
public class NotifySettlementRequest implements JsonInterface {

    /**
     * The transactionId that the settlement belongs to.
     * Can be empty if the payment transaction is canceled prior to the start of the OCPP transaction.
     */
    @Optional
    private String transactionId;

    /**
     * The payment reference received from the payment terminal and is used as the value for idToken.
     */
    @Required
    private String pspRef;

    /**
     * The status of the settlement attempt.
     */
    @Required
    private PaymentStatusEnum status;

    /**
     * Additional information from payment terminal/payment process.
     */
    @Optional
    private String statusInfo;

    /**
     * The amount that was settled, or attempted to be settled (in case of failure).
     */
    @Required
    private Float settlementAmount;

    /**
     * The time when the settlement was done.
     */
    @Required
    private Date settlementTime;

    /**
     *
     */
    @Optional
    private String receiptId;

    /**
     * The receipt URL, to be used if the receipt is generated by the payment terminal or the CS.
     */
    @Optional
    private String receiptUrl;

    /**
     * Company address associated with VAT number
     */
    @Optional
    private Address vatCompany;

    /**
     * VAT number for a company receipt.
     */
    @Optional
    private String vatNumber;

    /**
     *
     */
    @Optional
    private CustomData customData;


    public NotifySettlementRequest() {
    }


    public String getTransactionId() {
        return transactionId;
    }


    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId;
    }


    public String getPspRef() {
        return pspRef;
    }


    public void setPspRef(String pspRef) {
        this.pspRef = pspRef;
    }


    public PaymentStatusEnum getStatus() {
        return status;
    }


    public void setStatus(PaymentStatusEnum status) {
        this.status = status;
    }


    public String getStatusInfo() {
        return statusInfo;
    }


    public void setStatusInfo(String statusInfo) {
        this.statusInfo = statusInfo;
    }


    public Float getSettlementAmount() {
        return settlementAmount;
    }


    public void setSettlementAmount(Float settlementAmount) {
        this.settlementAmount = settlementAmount;
    }


    public Date getSettlementTime() {
        return settlementTime;
    }


    public void setSettlementTime(Date settlementTime) {
        this.settlementTime = settlementTime;
    }

    public String getReceiptId() {
        return receiptId;
    }

    public void setReceiptId(String receiptId) {
        this.receiptId = receiptId;
    }


    public String getReceiptUrl() {
        return receiptUrl;
    }


    public void setReceiptUrl(String receiptUrl) {
        this.receiptUrl = receiptUrl;
    }


    public Address getVatCompany() {
        return vatCompany;
    }


    public void setVatCompany(Address vatCompany) {
        this.vatCompany = vatCompany;
    }


    public String getVatNumber() {
        return vatNumber;
    }


    public void setVatNumber(String vatNumber) {
        this.vatNumber = vatNumber;
    }


    public CustomData getCustomData() {
        return customData;
    }


    public void setCustomData(CustomData customData) {
        this.customData = customData;
    }

    @Override
    public String toString() {
        return toJsonObject().toString();
    }

    @Override
    public JsonObject toJsonObject() {
        JsonObject json = new JsonObject();

        if (getTransactionId() != null) {
            json.addProperty("transactionId", getTransactionId());
        }
        json.addProperty("pspRef", getPspRef());

        json.addProperty("status", getStatus().toString());

        if (getStatusInfo() != null) {
            json.addProperty("statusInfo", getStatusInfo());
        }
        json.addProperty("settlementAmount", getSettlementAmount());

        json.addProperty("settlementTime", new SimpleDateFormat(DATE_FORMAT).format(getSettlementTime()));

        if (getReceiptId() != null) {
            json.addProperty("receiptId", getReceiptId());
        }
        if (getReceiptUrl() != null) {
            json.addProperty("receiptUrl", getReceiptUrl());
        }
        if (getVatCompany() != null) {
            json.add("vatCompany", getVatCompany().toJsonObject());
        }
        if (getVatNumber() != null) {
            json.addProperty("vatNumber", getVatNumber());
        }
        if (getCustomData() != null) {
            json.add("customData", getCustomData().toJsonObject());
        }

        return json;
    }

    @Override
    public void fromString(String jsonString) {
        JsonObject jsonObject = JsonParser.parseString(jsonString).getAsJsonObject();
        fromJsonObject(jsonObject);
    }

    @Override
    public void fromJsonObject(JsonObject jsonObject) {
        if (jsonObject.has("transactionId")) {
            setTransactionId(jsonObject.get("transactionId").getAsString());
        }

        if (jsonObject.has("pspRef")) {
            setPspRef(jsonObject.get("pspRef").getAsString());
        }

        if (jsonObject.has("status")) {
            setStatus(PaymentStatusEnum.valueOf(jsonObject.get("status").getAsString()));
        }

        if (jsonObject.has("statusInfo")) {
            setStatusInfo(jsonObject.get("statusInfo").getAsString());
        }

        if (jsonObject.has("settlementAmount")) {
            setSettlementAmount(jsonObject.get("settlementAmount").getAsFloat());
        }

        if (jsonObject.has("settlementTime")) {
            try {
                SimpleDateFormat dateFormat = new SimpleDateFormat(DATE_FORMAT);
                setSettlementTime(dateFormat.parse(jsonObject.get("settlementTime").getAsString()));
            } catch (ParseException e) {
                System.out.println("Invalid date format for settlementTime" + e);
            }
        }

        if (jsonObject.has("receiptId")) {
            setReceiptId(jsonObject.get("receiptId").getAsString());
        }

        if (jsonObject.has("receiptUrl")) {
            setReceiptUrl(jsonObject.get("receiptUrl").getAsString());
        }

        if (jsonObject.has("vatCompany")) {
            setVatCompany(new Address());
            getVatCompany().fromJsonObject(jsonObject.getAsJsonObject("vatCompany"));
        }

        if (jsonObject.has("vatNumber")) {
            setVatNumber(jsonObject.get("vatNumber").getAsString());
        }

        if (jsonObject.has("customData")) {
            setCustomData(new CustomData());
            getCustomData().fromJsonObject(jsonObject.getAsJsonObject("customData"));
        }
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (!(obj instanceof NotifySettlementRequest))
            return false;
        NotifySettlementRequest that = (NotifySettlementRequest) obj;
        return Objects.equals(this.pspRef, that.pspRef)
                && Objects.equals(this.statusInfo, that.statusInfo)
                && Objects.equals(this.vatCompany, that.vatCompany)
                && Objects.equals(this.settlementTime, that.settlementTime)
                && Objects.equals(this.customData, that.customData)
                && Objects.equals(this.settlementAmount, that.settlementAmount)
                && Objects.equals(this.receiptUrl, that.receiptUrl)
                && Objects.equals(this.receiptId, that.receiptId)
                && Objects.equals(this.transactionId, that.transactionId)
                && Objects.equals(this.status, that.status)
                && Objects.equals(this.vatNumber, that.vatNumber);
    }

    @Override
    public int hashCode() {
        int result = 1;
        result = 31 * result + (this.pspRef != null ? this.pspRef.hashCode() : 0);
        result = 31 * result + (this.statusInfo != null ? this.statusInfo.hashCode() : 0);
        result = 31 * result + (this.vatCompany != null ? this.vatCompany.hashCode() : 0);
        result = 31 * result + (this.settlementTime != null ? this.settlementTime.hashCode() : 0);
        result = 31 * result + (this.customData != null ? this.customData.hashCode() : 0);
        result = 31 * result + (this.settlementAmount != null ? this.settlementAmount.hashCode() : 0);
        result = 31 * result + (this.receiptUrl != null ? this.receiptUrl.hashCode() : 0);
        result = 31 * result + (this.receiptId != null ? this.receiptId.hashCode() : 0);
        result = 31 * result + (this.transactionId != null ? this.transactionId.hashCode() : 0);
        result = 31 * result + (this.status != null ? this.status.hashCode() : 0);
        result = 31 * result + (this.vatNumber != null ? this.vatNumber.hashCode() : 0);
        return result;
    }
}
