package maydo.ocpp.msgDef.Messages;


import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import maydo.ocpp.msgDef.DataTypes.CustomData;
import maydo.ocpp.msgDef.JsonInterface;
import maydo.ocpp.msgDef.annotations.Optional;

import java.util.Objects;

/**
 *
 */
public class NotifySettlementResponse implements JsonInterface {

    /**
     * The receipt URL if receipt generated by CSMS.
     * The Charging Station can QR encode it and show it to the EV Driver.
     */
    @Optional
    private String receiptUrl;

    /**
     * The receipt id if the receipt is generated by CSMS.
     */
    @Optional
    private String receiptId;

    /**
     *
     */
    @Optional
    private CustomData customData;


    public NotifySettlementResponse() {
    }


    public NotifySettlementResponse(String receiptUrl, String receiptId, CustomData customData) {
        super();
        this.receiptUrl = receiptUrl;
        this.receiptId = receiptId;
        this.customData = customData;
    }


    public String getReceiptUrl() {
        return receiptUrl;
    }


    public void setReceiptUrl(String receiptUrl) {
        this.receiptUrl = receiptUrl;
    }


    public String getReceiptId() {
        return receiptId;
    }


    public void setReceiptId(String receiptId) {
        this.receiptId = receiptId;
    }


    public CustomData getCustomData() {
        return customData;
    }


    public void setCustomData(CustomData customData) {
        this.customData = customData;
    }

    @Override
    public String toString() {
        return toJsonObject().toString();
    }

    @Override
    public JsonObject toJsonObject() {
        JsonObject json = new JsonObject();
        json.addProperty("receiptUrl", receiptUrl);
        json.addProperty("receiptId", receiptId);
        json.add("customData", customData.toJsonObject());
        return json;
    }

    @Override
    public void fromString(String jsonString) {
        JsonObject jsonObject = JsonParser.parseString(jsonString).getAsJsonObject();
        fromJsonObject(jsonObject);
    }

    @Override
    public void fromJsonObject(JsonObject jsonObject) {
        if (jsonObject.has("receiptUrl")) {
            this.receiptUrl = jsonObject.get("receiptUrl").getAsString();
        }

        if (jsonObject.has("receiptId")) {
            this.receiptId = jsonObject.get("receiptId").getAsString();
        }

        if (jsonObject.has("customData")) {
            this.customData = new CustomData();
            this.customData.fromJsonObject(jsonObject.getAsJsonObject("customData"));
        }

    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (!(obj instanceof NotifySettlementResponse))
            return false;
        NotifySettlementResponse that = (NotifySettlementResponse) obj;
        return Objects.equals(this.customData, that.customData)
                && Objects.equals(this.receiptUrl, that.receiptUrl)
                && Objects.equals(this.receiptId, that.receiptId);
    }

    @Override
    public int hashCode() {
        int result = 1;
        result = 31 * result + (this.customData != null ? this.customData.hashCode() : 0);
        result = 31 * result + (this.receiptUrl != null ? this.receiptUrl.hashCode() : 0);
        result = 31 * result + (this.receiptId != null ? this.receiptId.hashCode() : 0);
        return result;
    }
}
